FROM golang:1.17 as ecr-helper
RUN go install github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@main

FROM busybox as busybox
RUN which busybox

FROM portainer/agent
ENV HOME=/
COPY --from=busybox /bin/busybox /bin/busybox
RUN ["/bin/busybox","--install","-s","/bin"]
COPY --from=ecr-helper /go/bin/docker-credential-ecr-login /bin/docker-credential-ecr-login
COPY config.json /.docker/config.json
